### ISSUE TITLE
Golang support

### ISSUE THREAD

**Issue by thelooter** [piersolenski/telescope-import.nvim#25]
I really like this plugin. Currently it doesnt support go from what I can tell. Are there any plans to add that in the future?

**Comment by piersolenski** [comment]
Hey! I'm glad you enjoy it :-) I won't personally attempt to support every programming language, partly given the sheer amount in existence, but also because I am not familiar with the specific patterns and nuances of import patterns with each one.

A good starting point to see if your language of choice is already supported is to search GitHub for `telescope-import.nvim` and see if anyone else has added it under `custom_languages`.

If they haven't, then you can follow the instructions in https://github.com/piersolenski/telescope-import.nvim#%EF%B8%8F-configuration to add a language of your choosing.

If you do end up adding Go, a PR would be much appreciated!
